name: SpotMockServer
description: Spot mock server
homepage: https://github.com/MathiasMonstrey/spot-mock-server

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  async: ^2.2.0
  protobuf: ^1.0.1
  grpc: ^2.3.0
